# Site settings
title: Pagina personal
email: fiolorlando@gmail.com
description: "Desarrollador Web"
baseurl: ""
url: "http://overflow.github.io"
github_username:  overflow
facebook_username:  fiolorlando

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
